M48
; DRILL file {KiCad 7.0.9} date Wed Oct  9 10:00:51 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-09T10:00:51+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
%
G90
G05
T1
X4.9583Y-2.0045
X4.9583Y-2.91
X7.2417Y-2.0045
X7.2417Y-2.91
T0
M30
